version: '3.8'
services:
  user-db:
    image: postgres:alpine
    container_name: user-db
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5481:5432
    volumes:
      - ./db/user-db/data:/var/lib/postgresql/data
    restart: unless-stopped